### ISSUE TITLE
Unable to pick time: timePicker: true is not working

### ISSUE THREAD

**Issue by VikashPattnaik** [fragaria/angular-daterangepicker#170]
I am not able to show time picker using this directive. Was this feature missed intentionally?

**Comment by corali89** [comment]
1+

**Comment by vatsalpande** [comment]
+1

**Comment by villerdex** [comment]
+1

**Comment by BaamAadmi** [comment]
I assume it won't work if you are using  _autoApply: true_ ? It makes sense that _autoApply_ must be set to false in order to achieve proper functioning of the timepiece. 

In my project, I am dynamically applying _timepicker: true_ if Data Type is Datetime and for the same I have to switch _autapply: false_.  

```
this.dateOptions.timePicker =  (datatype === "DATETIME");
this.dateOptions.autoApply =  !(datatype === "DATETIME");
```
Cheers,
Sudeep
