### ISSUE TITLE
Calendar icon - Missing

### ISSUE THREAD

**Issue by xploregopi** [fragaria/angular-daterangepicker#77]
Hi,

 I need to show the calendar icon in before input tag. If we use icon how to click the icon show the same logic in input box. Please help me out.

**Comment by dsbaars** [comment]
I don't get it. I think you mean you have an input-group with a prepended icon as described on http://getbootstrap.com/components/#input-groups-basic? Bootstrap contains a calendar icon with glyphicons or you can chose to do it with font-awesome. That has nothing to do with this module.

I think you are talking about a missing function to trigger it programmatically, I already mentioned that shortly at #30. In my opinion this issue can be closed because it is invalid.

**Comment by AlenkaM** [comment]
Hello! I tried to use a version of icon which was suggested in #30, but icon click event makes the dropdown area blink as it was closed and reopened again. Is there any way to resolve it?
